# shared-workflows/.github/workflows/generate_task.yml

name: Generate Task Workflow

on:
  workflow_call:
    inputs:
      theme:
        description: 'Theme for the new task'
        required: true
        type: string
        default: 'Create a simple game application that includes the following functionalities: player movement, scoring system, and enemy interactions.'
      difficulty:
        description: 'Difficulty level for the new task'
        required: true
        type: string
        default: 'medium'
        # Expected values: basic, medium, hard
      language:
        description: 'Natural language for the task description'
        required: true
        type: string
        default: 'English'
    secrets:
      OPENAI_TOKEN:
        required: true
      GITHUB_TOKEN:
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-task-description:
    name: Generate Task Description
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.set-branch-name.outputs.branch_name }}
    steps:
      - name: Checkout Caller Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history for branch operations

      - name: Checkout Shared Workflows Repository
        uses: actions/checkout@v3
        with:
          repository: 'alinda-24/shared-workflows'  # Replace with your username/org and repo
          path: 'shared-workflows'
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai pytz

      - name: Generate Task Description
        id: generate-task-description
        env:
          OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TASK_DIFFICULTY: ${{ inputs.difficulty }}
          TASK_THEME: ${{ inputs.theme }}
          TASK_LANGUAGE: ${{ inputs.language }}
        run: |
          python shared-workflows/scripts/generate_task_description.py "${{ secrets.OPENAI_TOKEN }}"

      - name: Set Branch Name
        id: set-branch-name
        run: echo "branch_name=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_OUTPUT

  generate-solution:
    name: Generate Solution
    runs-on: ubuntu-latest
    needs: generate-task-description
    outputs:
      branch_name: ${{ steps.set-branch-name.outputs.branch_name }}
    steps:
      - name: Checkout Caller Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.generate-task-description.outputs.branch_name }}
          fetch-depth: 0  # Ensure full history

      - name: Checkout Shared Workflows Repository
        uses: actions/checkout@v3
        with:
          repository: 'alinda-24/shared-workflows'  # Replace with your username/org and repo
          path: 'shared-workflows'
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Generate Solution
        id: generate-solution
        env:
          OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python shared-workflows/scripts/generate_solution.py "${{ secrets.OPENAI_TOKEN }}" "${{ needs.generate-task-description.outputs.branch_name }}"

      - name: Set Branch Name
        id: set-branch-name
        run: |
          branch=$(git rev-parse --abbrev-ref HEAD)
          if [ -z "$branch" ]; then
            echo "branch_name=default-branch" >> $GITHUB_OUTPUT
          else
            echo "branch_name=$branch" >> $GITHUB_OUTPUT
          fi

  generate-tests:
    name: Generate Tests
    runs-on: ubuntu-latest
    needs: generate-solution
    outputs:
      branch_name: ${{ steps.set-branch-name.outputs.branch_name }}
    steps:
      - name: Checkout Caller Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.generate-solution.outputs.branch_name }}
          fetch-depth: 0  # Ensure full history

      - name: Checkout Shared Workflows Repository
        uses: actions/checkout@v3
        with:
          repository: 'alinda-24/shared-workflows'  # Replace with your username/org and repo
          path: 'shared-workflows'
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Generate Tests
        id: generate-tests
        env:
          OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python shared-workflows/scripts/generate_tests.py "${{ secrets.OPENAI_TOKEN }}" "${{ needs.generate-solution.outputs.branch_name }}"

      - name: Set Branch Name
        id: set-branch-name
        run: |
          branch=$(git rev-parse --abbrev-ref HEAD)
          if [ -z "$branch" ]; then
            echo "branch_name=default-branch" >> $GITHUB_OUTPUT
          else
            echo "branch_name=$branch" >> $GITHUB_OUTPUT
          fi

  adversarial-review:
    name: Adversarial Review - Improve Solution
    runs-on: ubuntu-latest
    needs: generate-solution
    steps:
      - name: Checkout Caller Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.generate-solution.outputs.branch_name }}
          fetch-depth: 0  # Ensure full history

      - name: Checkout Shared Workflows Repository
        uses: actions/checkout@v3
        with:
          repository: 'alinda-24/shared-workflows'  # Replace with your username/org and repo
          path: 'shared-workflows'
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Adversarial Review - Improve Solution
        env:
          OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python shared-workflows/scripts/adversarial_review.py "${{ secrets.OPENAI_TOKEN }}" "tasks/new_task.md" ".hidden_tasks"

  adversarial-test-review:
    name: Adversarial Review - Improve Tests
    runs-on: ubuntu-latest
    needs: generate-tests
    steps:
      - name: Checkout Caller Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.generate-tests.outputs.branch_name }}
          fetch-depth: 0  # Ensure full history

      - name: Checkout Shared Workflows Repository
        uses: actions/checkout@v3
        with:
          repository: 'alinda-24/shared-workflows'  # Replace with your username/org and repo
          path: 'shared-workflows'
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Adversarial Review - Improve Tests
        env:
          OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python shared-workflows/scripts/adversarial_tests.py "${{ secrets.OPENAI_TOKEN }}" "gen_test"

  generate-template-code:
    name: Generate Template Code
    runs-on: ubuntu-latest
    needs: adversarial-review
    steps:
      - name: Checkout Caller Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.adversarial-review.outputs.branch_name }}
          fetch-depth: 0  # Ensure full history

      - name: Checkout Shared Workflows Repository
        uses: actions/checkout@v3
        with:
          repository: 'alinda-24/shared-workflows'  # Replace with your username/org and repo
          path: 'shared-workflows'
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Generate Template Code
        env:
          OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python shared-workflows/scripts/generate_template_code.py "${{ secrets.OPENAI_TOKEN }}" "${{ needs.adversarial-review.outputs.branch_name }}"
